### ISSUE TITLE
json-to-string

### ISSUE THREAD

**Issue by ButuzGOL** [murvinlai/string-to-json#1]
Can you suggest json to string ?

**Comment by ButuzGOL** [comment]
I found https://npmjs.org/package/underscore.deep

**Comment by murvinlai** [comment]
JSON to string, you may use that module. (i haven't looked at it), or just do JSON.stringify or Util.inspect.  If more sophisticate, then you need to look for packages in npm.  I don't have anything in mind right now. :)
